[project]
name = "src"
version = "0.0.1"
description = "A Mini project to practice flask"
authors = [{name = "Farjhan Ahmed", email = "farjhanahmed@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}